.TH "src/1_0_load_mapini.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/1_0_load_mapini.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmap_ini\fP (t_map *map, int total)"
.br
.ti -1c
.RI "void \fBmap_ini_colors\fP (t_map *map)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void map_ini (t_map * map, int total)"

.SS "void map_ini_colors (t_map * map)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
