.TH "src/1_1_load_loadpoints.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/1_1_load_loadpoints.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBload_points\fP (char *line, t_map *map, int numline)"
.br
.ti -1c
.RI "int \fBvalid_point\fP (char *value)"
.br
.ti -1c
.RI "int \fBhas_hexcolors\fP (char *line)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int has_hexcolors (char * line)"

.SS "int load_points (char * line, t_map * map, int numline)"

.SS "int valid_point (char * value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
