.TH "src/1_2_load_gopolar.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/1_2_load_gopolar.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgo_polar\fP (t_map *map)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void go_polar (t_map * map)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
