.TH "src/1_2_load_colorize.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/1_2_load_colorize.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcolorize\fP (t_map *map)"
.br
.ti -1c
.RI "void \fBload_color\fP (int max, int min, t_point *point, t_colors colors)"
.br
.ti -1c
.RI "int \fBgradient\fP (int startcolor, int endcolor, int len, int pix)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void colorize (t_map * map)"

.SS "int gradient (int startcolor, int endcolor, int len, int pix)"

.SS "void load_color (int max, int min, t_point * point, t_colors colors)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
