.TH "src/1___map_load.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/1___map_load.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBload_map\fP (t_map *map, char *path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void load_map (t_map * map, char * path)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
