.TH "src/3_1__draw_background.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_1__draw_background.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcopy_map\fP (t_point *src, t_point *dst, int len)"
.br
.ti -1c
.RI "int \fBget_color\fP (t_meta *meta, int color)"
.br
.ti -1c
.RI "void \fBgenerate_background\fP (t_meta *meta, int backcolor, int menucolor)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void copy_map (t_point * src, t_point * dst, int len)"

.SS "void generate_background (t_meta * meta, int backcolor, int menucolor)"

.SS "int get_color (t_meta * meta, int color)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
