.TH "src/3_2_1_parse_geometry.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_2_1_parse_geometry.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBz_division\fP (t_point *proyect, float divisor, int len)"
.br
.ti -1c
.RI "void \fBbending\fP (t_point *points, int len, float range)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bending (t_point * points, int len, float range)"

.SS "void z_division (t_point * proyect, float divisor, int len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
