.TH "src/3_2_3_parse_scale.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_2_3_parse_scale.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBscale\fP (t_point *points, int scale, int len)"
.br
.ti -1c
.RI "void \fBtraslate\fP (t_point *points, t_point move, int len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void scale (t_point * points, int scale, int len)"

.SS "void traslate (t_point * points, t_point move, int len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
