.TH "src/3_2_2_parse_matrix.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_2_2_parse_matrix.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrotate_x\fP (t_point *points, t_point *projection, float ang, int len)"
.br
.ti -1c
.RI "void \fBrotate_y\fP (t_point *points, t_point *projection, float ang, int len)"
.br
.ti -1c
.RI "void \fBrotate_z\fP (t_point *points, t_point *projection, float ang, int len)"
.br
.ti -1c
.RI "void \fBortogonal_projection\fP (t_point *points, t_point *projection, int len)"
.br
.ti -1c
.RI "t_point \fBmatrix3_multp\fP (float matrix[3][3], t_point point)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "t_point matrix3_multp (float matrix[3][3], t_point point)"

.SS "void ortogonal_projection (t_point * points, t_point * projection, int len)"

.SS "void rotate_x (t_point * points, t_point * projection, float ang, int len)"

.SS "void rotate_y (t_point * points, t_point * projection, float ang, int len)"

.SS "void rotate_z (t_point * points, t_point * projection, float ang, int len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
