.TH "src/3_3_2_drawning_doted.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_3_2_drawning_doted.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdoted\fP (t_meta *meta, t_point *proyect)"
.br
.ti -1c
.RI "void \fBdraw_dot\fP (t_meta *meta, t_point point, int radius)"
.br
.ti -1c
.RI "void \fBdot_util\fP (t_meta *meta, t_point pixel, t_point point, int coord)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dot_util (t_meta * meta, t_point pixel, t_point point, int coord)"

.SS "void doted (t_meta * meta, t_point * proyect)"

.SS "void draw_dot (t_meta * meta, t_point point, int radius)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
