.TH "src/3_3_2_drawning_myputpixel.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_3_2_drawning_myputpixel.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_putpixel\fP (t_meta *meta, t_point pixel)"
.br
.ti -1c
.RI "void \fBset_color\fP (char *buffer, int endian, int color, int alpha)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_putpixel (t_meta * meta, t_point pixel)"

.SS "void set_color (char * buffer, int endian, int color, int alpha)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
