.TH "src/3_3__drawning_gofit.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_3__drawning_gofit.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgo_fit\fP (t_meta *meta, t_point *proyect)"
.br
.ti -1c
.RI "int \fBlimits\fP (t_point *points, int len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void go_fit (t_meta * meta, t_point * proyect)"

.SS "int limits (t_point * points, int len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
