.TH "src/3_3_1_drawning_wired.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/3_3_1_drawning_wired.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwired\fP (t_meta *meta, t_point *wire)"
.br
.ti -1c
.RI "void \fBwire_line\fP (t_point *point, t_meta *meta, int density, int line)"
.br
.ti -1c
.RI "int \fBdraw_line\fP (t_meta *meta, t_point start, t_point end)"
.br
.ti -1c
.RI "int \fBvalid_pixel\fP (t_point pixel)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int draw_line (t_meta * meta, t_point start, t_point end)"

.SS "int valid_pixel (t_point pixel)"

.SS "void wire_line (t_point * point, t_meta * meta, int density, int line)"

.SS "void wired (t_meta * meta, t_point * wire)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
