.TH "src/4___views_bonus.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/4___views_bonus.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBisometric\fP (t_map *map)"
.br
.ti -1c
.RI "void \fBparallel\fP (t_map *map)"
.br
.ti -1c
.RI "void \fBspherize\fP (t_map *map, t_point *points)"
.br
.ti -1c
.RI "void \fBshadow\fP (t_point *points, int len)"
.br
.ti -1c
.RI "void \fBgenerate_stars\fP (t_meta *meta)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void generate_stars (t_meta * meta)"

.SS "void isometric (t_map * map)"

.SS "void parallel (t_map * map)"

.SS "void shadow (t_point * points, int len)"

.SS "void spherize (t_map * map, t_point * points)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
