.TH "src/5___control_keys2.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/5___control_keys2.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBangle_control\fP (int key, t_meta *meta)"
.br
.ti -1c
.RI "void \fBcontrol_colorscheme\fP (int key, t_map *map)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void angle_control (int key, t_meta * meta)"

.SS "void control_colorscheme (int key, t_map * map)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
