.TH "src/5___control_keys.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/5___control_keys.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBkey_press\fP (int key, void *param)"
.br
.ti -1c
.RI "int \fBkey_release\fP (int key, void *param)"
.br
.ti -1c
.RI "void \fBcontrol_keys1\fP (int key, t_meta *meta)"
.br
.ti -1c
.RI "void \fBcontrol_keys2\fP (int key, t_meta *meta)"
.br
.ti -1c
.RI "void \fBcontrol_keys3\fP (int key, t_meta *meta)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void control_keys1 (int key, t_meta * meta)"

.SS "void control_keys2 (int key, t_meta * meta)"

.SS "void control_keys3 (int key, t_meta * meta)"

.SS "int key_press (int key, void * param)"

.SS "int key_release (int key, void * param)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
