.TH "src/5___draw_menu.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/5___draw_menu.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdraw_colorscheme\fP (t_meta *meta)"
.br
.ti -1c
.RI "void \fBdraw_mapinfo\fP (t_meta *meta)"
.br
.ti -1c
.RI "void \fBdraw_controls\fP (t_meta *meta)"
.br
.ti -1c
.RI "void \fBdraw_info\fP (t_meta *meta)"
.br
.ti -1c
.RI "void \fBdraw_menu\fP (t_meta *meta)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void draw_colorscheme (t_meta * meta)"

.SS "void draw_controls (t_meta * meta)"

.SS "void draw_info (t_meta * meta)"

.SS "void draw_mapinfo (t_meta * meta)"

.SS "void draw_menu (t_meta * meta)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
