.TH "src/5___control_mouse.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/5___control_mouse.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmouse_press\fP (int button, int x, int y, void *param)"
.br
.ti -1c
.RI "int \fBmouse_release\fP (int button, int x, int y, void *param)"
.br
.ti -1c
.RI "int \fBmouse_move\fP (int x, int y, void *param)"
.br
.ti -1c
.RI "void \fBangle\fP (float *ang, float value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void angle (float * ang, float value)"

.SS "int mouse_move (int x, int y, void * param)"

.SS "int mouse_press (int button, int x, int y, void * param)"

.SS "int mouse_release (int button, int x, int y, void * param)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
