.TH "src/6___utils.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/6___utils.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_nbr\fP (t_meta *meta, int x, int y, int nbr)"
.br
.ti -1c
.RI "void \fBprint_str\fP (t_meta *meta, int x, int y, char *str)"
.br
.ti -1c
.RI "void \fBterminate\fP (char *s)"
.br
.ti -1c
.RI "void \fBterminate1\fP (char *s, t_meta *meta)"
.br
.ti -1c
.RI "int \fBhalt_exit_program\fP (void *param)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int halt_exit_program (void * param)"

.SS "void print_nbr (t_meta * meta, int x, int y, int nbr)"

.SS "void print_str (t_meta * meta, int x, int y, char * str)"

.SS "void terminate (char * s)"

.SS "void terminate1 (char * s, t_meta * meta)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
