.TH "src Directory Reference" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1_0_load_mapini\&.c\fP"
.br
.ti -1c
.RI "file \fB1_0_load_mapsize\&.c\fP"
.br
.ti -1c
.RI "file \fB1_1_load_getpoints\&.c\fP"
.br
.ti -1c
.RI "file \fB1_1_load_loadpoints\&.c\fP"
.br
.ti -1c
.RI "file \fB1_2_load_colorize\&.c\fP"
.br
.ti -1c
.RI "file \fB1_2_load_gopolar\&.c\fP"
.br
.ti -1c
.RI "file \fB1___map_load\&.c\fP"
.br
.ti -1c
.RI "file \fB2___sys_ini\&.c\fP"
.br
.RI "System Initialization Source File\&. "
.ti -1c
.RI "file \fB3_1__draw_background\&.c\fP"
.br
.ti -1c
.RI "file \fB3_2_1_parse_geometry\&.c\fP"
.br
.ti -1c
.RI "file \fB3_2_2_parse_matrix\&.c\fP"
.br
.ti -1c
.RI "file \fB3_2_3_parse_scale\&.c\fP"
.br
.ti -1c
.RI "file \fB3_2__draw_parsemap\&.c\fP"
.br
.RI "This file contains the implementation of functions to modify points in a space\&. "
.ti -1c
.RI "file \fB3_3_1_drawning_wired\&.c\fP"
.br
.ti -1c
.RI "file \fB3_3_2_drawning_doted\&.c\fP"
.br
.ti -1c
.RI "file \fB3_3_2_drawning_myputpixel\&.c\fP"
.br
.ti -1c
.RI "file \fB3_3__draw_drawning\&.c\fP"
.br
.RI "This file contains the implementation of drawing functionalities\&. "
.ti -1c
.RI "file \fB3_3__drawning_gofit\&.c\fP"
.br
.ti -1c
.RI "file \fB3___map_draw\&.c\fP"
.br
.RI "This file contains functions and logic for drawing maps\&. "
.ti -1c
.RI "file \fB4___views_bonus\&.c\fP"
.br
.ti -1c
.RI "file \fB5___control_keys\&.c\fP"
.br
.ti -1c
.RI "file \fB5___control_keys2\&.c\fP"
.br
.ti -1c
.RI "file \fB5___control_mouse\&.c\fP"
.br
.ti -1c
.RI "file \fB5___draw_menu\&.c\fP"
.br
.ti -1c
.RI "file \fB6___utils\&.c\fP"
.br
.ti -1c
.RI "file \fB_main\&.c\fP"
.br
.in -1c
