.TH "src/_main.c" 3 "Fri Mar 7 2025 07:42:48" "fdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/_main.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/fdf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argv, char **argc)"
.br
.RI "Implementation of the FdF project from 42 school\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argv, char ** argc)"

.PP
Implementation of the FdF project from 42 school\&. 
.PP
\fBDetails:\fP
.RS 4

.IP "\(bu" 2
The FdF project is a graphical representation project that involves creating a wireframe model of a 3D landscape from a given set of coordinates\&. The goal is to display the model in a window and allow for basic interactions such as zooming and rotating\&.
.PP
.RE
.PP
\fBUsage Make: make MAP=[map]\fP
.RS 4

.IP "\(bu" 2
[42] make MAP=42
.IP "\(bu" 2
[mars] make MAP=mars
.IP "\(bu" 2
[earth] make MAP=earth
.IP "\(bu" 2
[fractol] make MAP=fractol
.PP
.RE
.PP
.IP "\(bu" 2
[mandel] make MAP=mandel
.PP
.PP
\fBUsage Program: \&./fdf maps/[X]\fP
.RS 4

.IP "\(bu" 2
[parm2] \fBargv:\fP file containing the coordinates of the landscape\&.
.IP "\(bu" 2
return: \fBreturn\fP void
.IP "\(bu" 2
[X]:
.IP "  \(bu" 4
maps/42\&.fdf
.IP "  \(bu" 4
maps/mars\&.fdf
.IP "  \(bu" 4
maps/fract\&.fdf
.IP "  \(bu" 4
maps/julia\&.fdf 
.PP
.nf
make &&\\
\&./fdf maps/42\&.fdf

.fi
.PP

.PP

.PP
.RE
.PP
\fBUsage Make:\fP
.RS 4

.IP "\(bu" 2
[static analysis] make linting
.IP "\(bu" 2
[leaks] make leaks 
.PP
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fdf from the source code\&.
